### ISSUE TITLE
VectorStore.as_retriever() missing.

### ISSUE THREAD

**Issue by Vipuld2t** [Eurelis/Eurelis-Langchain-SolR-VectorStore#1]
I tried to run the code as described in the given link (https://pypi.org/project/eurelis-langchain-solr-vectorstore/), but I am not able to run it and get the results.

Can we have some clarity on the  parameter in the retriever, which is defined as solr.as_retriever(search_kwargs: {'language': 'en', year: 2000})?"

**Comment by jeromediaz** [comment]
@Vipuld2t we will update the documentation,

it should have been written
retriever = vector_store.as_retriever() # basic retriever
or
retriever = vector_store.as_retriever(search_kwargs= {'filter': {'language': 'en', 'year': 2000}}) # retriever filtering results to have only documents with language = en and year = 2000

does it helps you?
